# Generated by Django 4.0.4 on 2022-04-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
